version: 2
jobs:
  build:
    machine:
      image: ubuntu-2204:2023.07.2
    steps:
      - checkout
      - run: go install github.com/mitchellh/gox@v1.0.1
      - run: go install github.com/tcnksm/ghr@v0.16.0
      - run: sudo apt-get update && sudo apt-get install p7zip-full
      - run: sudo bash -c "curl -L --output - https://github.com/crazy-max/xgo/releases/download/v0.30.0/xgo_0.30.0_linux_amd64.tar.gz | tar xvz -C /usr/local/bin/ ./xgo"
      - restore_cache: # restores saved cache if no changes are detected since last run
          keys:
            - go-mod-v4-{{ checksum "go.sum" }}
      - run:
          command: |
            sudo chmod 666 /var/run/docker.sock
            if [ -f /var/run/docker-temp.sock ]; then
              sudo chmod 666 /var/run/docker-temp.sock
            fi
      - run:
          command: |
            export GOPATH=/home/circleci/.go_workspace
            make dist
      - save_cache:
          key: go-mod-v4-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
      - run:
          name: create release
          command: |
            if [ "$CIRCLE_TAG" ]; then
              mkdir -p dist
              mv force*.zip dist
              ghr -t $GITHUB_TOKEN -u $CIRCLE_PROJECT_USERNAME -r $CIRCLE_PROJECT_REPONAME --replace $CIRCLE_TAG dist/
            else
              echo "No tag"
            fi
workflows:
  version: 2
  build-workflow: # the name of our workflow
    jobs: # the jobs that we are sequencing.
      - build:
          filters:
            tags:
              only: /^v.*/
